config/routes.rb
Rails.application.routes.draw do
  resources :courses

end

app/models/course.rb
#require 'elasticsearch/model'

class Course < ActiveRecord::Base
	# include Elasticsearch::Model
	# include Elasticsearch::Model::Callbacks
	# after_save :refresh_index
	# after_create :refresh_index
	# after_update :refresh_index

	# def refresh_index
 #    	Course.__elasticsearch__.refresh_index!
	# end
	
	searchable do
		text :title, :category
		float :duration
		time :published_at
	end
end





# Course.__elasticsearch__.create_index!

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index

    @courses = if params[:q].present? || params[:search] && (params[:search][:title].present? || params[:search][:category].present?)
      # ElasticSearcher.new.call(params).courses
      SunspotSearcher.new.call(params).courses
    else
      Course.page(params[:page] || 1).per(15).all
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:title, :category, :duration, :published_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
	def options_for_published_at
		options_for_select([
			[" -- Select --"],
			["week","week"],
			["month","month"],
			["year","year"]
		])
	end
end

app/views/courses/_form.html.haml
= form_for @course do |f|
  - if @course.errors.any?
    #error_explanation
      %h2= "#{pluralize(@course.errors.count, "error")} prohibited this course from being saved:"
      %ul
        - @course.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :category
    = f.text_field :category
  .field
    = f.label :duration
    = f.text_field :duration
  .field
    = f.label :published_at
    = f.datetime_select :published_at
  .actions
    = f.submit 'Save'

app/views/courses/_search.html.haml
=form_tag courses_path, method: :get do
	%p
		=text_field :q,"",placeholder: "Search Term" 
		=button_tag "Search"
	%fieldset
		%legend Advanced Search

		%p 
			=text_field_tag "search[title]","",class: "form-control", placeholder: "Title"
		%p
			=text_field_tag "search[category]","",class: "form-control", placeholder: "Category"

		%p.input-group.col-md-4
			=text_field_tag "search[duration_start]","",class: "form-control",placeholder: "Duration Start"
			%span.input-group-addon
				&rarr;
			=text_field "search[duration_end]","",class: "form-control", placeholder: "Duration End"

		%p.input-group.input-daterange.date.col-md-4
			=text_field_tag "search[published_at_start]","",class: "form-control",placeholder: "Satrt published At"
			%span.input-group-addon
				&rarr;
			=text_field_tag "search[published_at_end]","",class: "form-control",placeholder: "End published at"

		%p 
			Published last:
			=select_tag "search[published_at_last]", options_for_published_at

		=button_tag "Search"

app/views/courses/edit.html.haml
%h1 Editing course

= render 'form'

= link_to 'Show', @course
\|
= link_to 'Back', courses_path

app/views/courses/index.html.haml
%h1 Listing courses
=render "search"
%table.table.table-hover
  %thead
    %tr
      %th Title
      %th Category
      %th Duration
      %th Published at

  %tbody
    - @courses.each do |course|
      %tr
        %td= course.title
        %td= course.category
        %td= course.duration
        %td= course.published_at
%br
=paginate @courses, theme: "twitter-bootstrap-3"
%p= link_to 'New Course', new_course_path

app/views/courses/new.html.haml
%h1 New course

= render 'form'

= link_to 'Back', courses_path

app/views/courses/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @course.title
%p
  %b Category:
  = @course.category
%p
  %b Duration:
  = @course.duration
%p
  %b Published at:
  = @course.published_at

= link_to 'Edit', edit_course_path(@course)
\|
= link_to 'Back', courses_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sherlock</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<%= yield %>
</div>
</body>
</html>